import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import { getData } from "../utils/fetchData";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData("api/v1/events");
  const res = req.data;

  return {
    props: { data: res },
  };
}
